artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/main/risk.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_tranfomation:
  root_dir: artifacts/data_tranfomation
  data_path: artifacts/data_ingestion/risk.xls