artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/main/risk.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_tranfomation:
  root_dir: artifacts/data_tranfomation
  data_path: artifacts/data_ingestion/risk.xls

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_tranfomation/train.csv
  test_data_path: artifacts/data_tranfomation/test.csv
  model_name: model.joblib
